---
title: "Bibliotecas - *Informações*"
date: "julho de 2015"
output: 
  html_document: 
    keep_md: yes
    theme: spacelab
    toc: yes
---
<style type="text/css">
 pre:not([class]){
 color:black;
 background-color:pink;
 }
</style>
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
    tidy = FALSE, 
    results = "markup", # hold
    fig.path = "graphs/",
    dpi = 100,
    fig.align = "center",
    fig.show = "asis", # hold
    comment = NA,
    warning = FALSE,
    cache = TRUE)
```
***
***
# gWidgets
**API gWidgets para construção de conjuntos de ferramentas independentes, GUIs interativas**

gWidgets fornece um conjunto de ferramentas independentes API para a construção de GUIs interativas. Ao menos um dos 'gWidgetsXXX packages', como o gWidgetstcltk, precisa ser instalado. Alguns ícones estão em empréstimo do [`projeto scigraphica`](http://scigraphica.sourceforge.net).

Versão: 0.0-54

Mantenedor: John Verzani ( jverzani\@gmail.com )

[**CRAN - Package gWidgets**](http://cran.r-project.org/web/packages/gWidgets/index.html)

***
***
# rpanel
**Controles interativos simples para R utilizando a biblioteca tcltk**

rpanel fornece um conjunto de funções para a construção de controles GUI simples para funções R. Estas são construídas no pacote tcltk. Usos podem incluir a mundança de um parâmetro em um gráfico animando-lo com um deslizador ou um "doublebutton", até mais panels de controle sofisticados. Algumas funções para específicas tarefas gráficas, referidas como 'cartoons', são disponibilizadas.

Versão: 1.1-3

Mantenedor: Adrian Bowman ( adrian.bowman\@glasgow.ac.uk )

[**CRAN - Package rpanel**](http://cran.r-project.org/web/packages/rpanel/index.html)

***
***
# shiny
**Estrutura de aplicação WEB para R**

Torna incrivelmente fácil a construção de aplicações web interativas com R. "Reativa" automática de ligação entre entradas (inputs) e saídas (outputs) e extensos widgets pré-construídos tornam possível a construção de bonitas, responsivas, e poderosas aplicações com o mínimo esforço.

Versão: 0.12.1

Mantenedor: Winston Chang ( winston\@rstudio.com )

[**CRAN - Package shiny**](http://cran.r-project.org/web/packages/shiny/index.html)

***
***
# manipulate
**Gráficos interativos para RStudio**

Funções gráficas interativas para uso dentro do RStudio. A função manipulate aceita uma expressão gráfica e um conjunto de controles (por exemplo deslizadores (slider), apanhadores (picker), caixas de seleção (checkbox), ou botões (button)) que são utilizados para alterar dinamicamente valores dentro da expressão. Quando um valor é alterado utilizando seu controle correspondente a expressão é automaticamente re-executada e o gráfico é redesenhado.

Versão: 1.0.1

Mantenedor: JJ Allaire ( jj\@rstudio.com )

[**CRAN - Package manipulate**](http://cran.r-project.org/web/packages/manipulate/index.html)

***
***
# animation
**Uma galeria de animações em estatística e utilitários para a criação de animações**

Este pacote contem uma variedade de funções para animações em estatística, cobrindo áreas como a teoria da probabilidade, estatística matemática, estatística multivariada, estatística não paramétrica, pesquisa por amostragem, modelos lineares, séries temporais, estatística computacional, data mining e machine learning. Estas funções podem ser úteis no ensino de estatística e na análise de dados. Também é fornecido nesto pacote uma série de opções para salvar animações em vários formatos, como por exemplo, Flash, GIF, páginas HTML, PDF e vídeos (saveSWF(), saveGIF(), saveHTML(), saveLatex(), e saveVideo() respectivamente). Animações em PDF podem ser inseridas dentro do Sweave/knitr facilmente.

Versão: 2.3

Mantenedor: Yihui Xie ( xie\@yihui.name )

[**CRAN - Package animation**](http://cran.r-project.org/web/packages/animation/index.html)

***
***
# rgl
**Visualização 3D utilizando OpenGL**

Fornece funções médio e alto nível para gráficos interativos 3D, incluindo funções modeladas na base gráfica (plot3d(), etc.) bem como funções para a construção de representações de objetos geométricos (cube3d(), etc.). As saídas podem ser na tela utilizando OpenGL, ou para vários formatos de arquivos 3D padrão incluindo WebGL, PLY, OBJ, STL bem como os formatos de imagem 2D, incluindo PNG, Postscript, SVG, PGF.

Versão: 0.95.1247

Mantenedor: Duncan Murdoch ( murdoch\@stats.uwo.ca )

[**CRAN - Package rgl**](http://cran.r-project.org/web/packages/rgl/index.html)

***
***
# googleVis
**Interface R para gráficos Google**

Interface R para gráficos Google API, possibilitando que usuários criem gráficos interativos baseados em data frames. Os gráficos são exibidos localmente via o R HTTP help server. Um navegador moderno com conexão Interney é requerido e para alguns gráficos um Flash player. Os dados permanecem locais e não são enviados ao Google.

Versão: 0.5.9

Mantenedor: Markus Gesmann ( markus.gesmann\@googlemail.com )

[**CRAN - Package googleVis**](http://cran.r-project.org/web/packages/googleVis/index.html)
